### ISSUE TITLE
Minor emoji ID tweaks

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#245]
- Please change the pipe color from black to gray per https://zpl.io/awDW4eJ
- Make the emoji IDs closer to one another than they are to the pipes, so they're more clearly in chunks of 3. Right now there seems to be the same spacing between each emoji as there is between the emoji and the pipe
- The shadow of the white Emoji ID component is different from the design, and it's unclear to me but there may be a stroke around it too (please click on the component to see the shadow attributes): zpl.io/bWn9o6n

**Comment by kukabi** [comment]
@talmahaj First two issues should be fixed by the latest PR. Re the shadow under emoji id component: I'm currently using the native view elevation property, so the shadow is displayed by Android. Other way would be to get shadow graphic assets from Karim and apply. I would prefer to go with native shadows, please let me know if the look difference is unacceptable, if not then I'll ping Karim for the assets.

**Comment by talmahaj** [comment]
In that case it’s totally fine to leave as is, thanks for explaining!
