### ISSUE TITLE
Persist Tor identity & reuse.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#270]
Currently the identity does not get persisted & the param to the `FFITransportType` constructor is blank at every start-up.

**Comment by Tas4tari** [comment]
@kukabi How best can I test this to ensure it is working as expected?

**Comment by kukabi** [comment]
@Tas4tari Stan can definitely confirm this.

**Comment by sdbondi** [comment]
@Tas4tari To test this: 
1. send a transaction from the android wallet (wallet A) to another wallet (any will do - base node, ios, android wallet - let's call it wallet B)
2. wait for it to go through to pending  
3. force close the android wallet so that the tari background service closes
4. send a transaction from wallet B back to the android wallet (wallet A)
5. quickly open up wallet A again

If successful, then wallet A's address has not changed so the transaction should go through pretty quickly

**Comment by Tas4tari** [comment]
@sdbondi Thanks, will test it this way

**Comment by Tas4tari** [comment]
Tested as per the instructions, transaction received successfully

**Comment by Anziskavds** [comment]
I was also bust testing this and also found that it tested successfully as per the instructions.
