### ISSUE TITLE
[Feature] Ability to cancel transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#295]
@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/tari/issues/1743)

@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/wallet-android/issues/292)

**Comment by Tas4tari** [comment]
**Tested on Huawei P30 lite, TESTNET V0.1.11-jnLibs-0.9.2**

Cancel Transaction button should appear to Sender as soon as transaction is initially sent, and only disappear once transaction is broadcast to mem-pool: **Tested successfully - when status changed to "Completing Final processing...the Cancel link was no longer visible**

When user hits Cancel Transaction button, a standard alert should appear reading:
“Are you sure?”
“Your recipient will be notified of the cancellation.”
“Not now” “Yes, Cancel” : **Tested successfully**

Cancelled and Expired transactions should appear in the transactions list for both the sender AND receiver, and both with the same style (grey pill, no + or - sign) : **Unable to test because when I cancel a transaction, the transaction is no longer visible within my transaction list**

Transaction detail page should read “Payment Cancelled” or “Payment Expired” respectively, with the “From” or “To” indicating to user which way the payment was sent. **Tested Unsuccessfully as the transaction is no longer visible on my Transaction list therefore I am unable to navigate to the TDS**

When transaction cancelled by sender, send push notification to recipient: "Your transaction was cancelled” “The sender cancelled the transaction before it was finalized, so the tXTR was returned to them” **Testing in progress (Will update shortly)**

**Comment by nyarian** [comment]
@Tas4tari Full cancelled transactions support is not yet implemented below the FFI layer, so only the opportunity to cancel a pending outbound transaction was released now as was discussed - without statuses support, push notifications and home screen TX list appearance. So I am actually not sure if the whole ticket should be in UAT.

**Comment by Tas4tari** [comment]
@nyarian So for now it's just the cancelling correct? Also will the user receive a push notification when the sender has cancelled the transaction?

**Comment by nyarian** [comment]
@Tas4tari currently cancellation only, yes. Push notifications should not appear now, they will be implemented along with TX list support and statuses on TX details (expired, cancelled) when the appropriate support will be available through the FFI layer.

**Comment by Tas4tari** [comment]
@nyarian Awesome thanks, so the cancellation is working which is fine for now. Will update the above comments :)

**Comment by Tas4tari** [comment]
As per above comments, cancellation is working
