### ISSUE TITLE
Notifications never show known aliases

### ISSUE THREAD

**Issue by CjS77** [tari-project/wallet-android#300]
## Behaviour:

When a notification is received, the emoji id is displayed. This is irrespective of whether the id in already in my contacts list or not.

## Expected behaviour:
Use the contact alias.
e.g. the notification should say "You received Tari from Bob"

**Comment by Tas4tari** [comment]
Tested  on Android, device Huawei P30 lite
v0.1.10-jnlLibs-0.9.1
@kukabi @nyarian The notifications are not received as per the expected behaviour listed above (See example):
Use the contact alias.
e.g. the notification should say "You received Tari from Bob"
They appear as per the screenshots below.
@talmahaj Can you confirm if this fine.
![Screenshot_20200506_144248_com huawei android launcher](https://user-images.githubusercontent.com/50987039/81178353-5b76a000-8fa8-11ea-9e40-d98c12e24a45.jpg)
![Screenshot_20200506_144216_com huawei android launcher](https://user-images.githubusercontent.com/50987039/81178392-67626200-8fa8-11ea-8bd9-a5a0ca4f38d6.jpg)

**Comment by Tas4tari** [comment]
Undergoing more testing to confirm correct behaviour

**Comment by Tas4tari** [comment]
Aliases show successfully
