### ISSUE TITLE
[Feature] Open TTL Store in in-app browser

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#356]
@talmahaj commented on [Tue May 12 2020](https://github.com/tari-project/wallet-ios/issues/369)

See [parent](https://github.com/tari-project/tari/issues/1843)

**Comment by Tas4tari** [comment]
Tested on Huawei P30 lite on v0.1.14 of the app:
**Acceptance Criteria**

- When tapping to open the TTL store from the modal in the app, an in-app browser should slide up from the bottom of the screen (like in Instagram or Pinterest) rather than opening the link in the user's default browser: **Tested successfully**
- Users should be able to hit the X icon on the top left or swipe down on the drawer to close the browser: **Tested successfully**
- Users should be able to navigate forward and back with the arrows at the bottom of the in-app browser: **Arrows are initially greyed out however when a user clicks on a product the arrow becomes visible and user can click it to go back to the homescreen**
- Back and/or forward arrow should be color #B8B8B8 when disabled (that is, when user cannot navigate forward or back): **Tested successfully**
- Users should be able to hit the Share icon to open their OS's default sharesheet (android) or share extension (ios) to share the store, get the link, or open it in their browser: **Tested successfully**

**Test Videos:**
TTL Store: 
https://drive.google.com/file/d/1s-kyN0csFcoddRWtLwBosNqzjG93hx7x/view?usp=sharing
Arrow Navigation: https://drive.google.com/file/d/1M7t2LJv5z0p0QZ3aZ7zUiJNAF7tWHF7N/view?usp=sharing
