### ISSUE TITLE
[Feature] Backup and restore wallet: Back up prompt modal

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#408]
See [parent](https://github.com/tari-project/tari/issues/1906)

**Comment by Tas4tari** [comment]
**Back up prompt modal**

**Acceptance Criteria**

- When user accepts their third tXTR transaction (that is, their first transaction NOT from the faucet), they should see the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caa4e8916298490df31
- When user reaches 8,000+ tXTR, AND it’s their fourth accepted transaction or later (otherwise they’ll see the first modal above) display the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca94e8916298490ded9
- When user reaches 25,000+ tXTR, AND it’s their 5th accepted transaction or later, display the same modal with the following copy: "Further secure your backups" "Given the amount of money in your wallet, you should password-protect your backups so they're safe even if your iCloud is compromised." "Secure Backups" "Not now" (replace iCloud with Google Drive for Android)
- The modals above should NOT appear if the user has already connected their cloud account
- Hitting Back Up Wallet should send the user to the backup section within Settings: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be

**Comment by talmahaj** [comment]
@Tas4tari updated specs to override above:

**Back up prompt modal**

**Acceptance Criteria**

- When user accepts their third tXTR transaction (that is, their first transaction NOT from the faucet), they should see the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caa4e8916298490df31
- When user reaches 8,000+ tXTR, AND it’s their fourth accepted transaction or later (otherwise they’ll see the first modal above) display the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca94e8916298490ded9
- When user reaches 25,000+ tXTR, AND it’s their 5th accepted transaction or later, display the same modal with the following copy: "Further secure your backups" "Given the amount of money in your wallet, you should password-protect your backups so they're safe even if your iCloud is compromised." "Secure Backups" "Not now" (replace iCloud with Google Drive for Android)
- The first two modals above should NOT appear if the user has already connected their cloud account.
- The third modal about encrypted backups should only appear if user has cloud backups enabled AND does not have the backups encrypted yet
- Hitting Back Up Wallet should send the user to the backup section within Settings: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be

These are also in the parent so we can delete the comments

**Comment by Tas4tari** [comment]
Testing on Huawei P30 lite, app version: v0.3.0-jnLibs-0.15.2
**Back up prompt modal**

**Acceptance Criteria**

When user accepts their third tXTR transaction (that is, their first transaction NOT from the faucet), they should see the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caa4e8916298490df31
When user reaches 8,000+ tXTR, AND it’s their fourth accepted transaction or later (otherwise they’ll see the first modal above) display the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca94e8916298490ded9
When user reaches 25,000+ tXTR, AND it’s their 5th accepted transaction or later, display the same modal with the following copy: "Further secure your backups" "Given the amount of money in your wallet, you should password-protect your backups so they're safe even if your iCloud is compromised." "Secure Backups" "Not now" (replace iCloud with Google Drive for Android)
The first two modals above should NOT appear if the user has already connected their cloud account.
The third modal about encrypted backups should only appear if user has cloud backups enabled AND does not have the backups encrypted yet
Hitting Back Up Wallet should send the user to the backup section within Settings: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be

**Comment by Tas4tari** [comment]
Ticket created for Requirement 1: 
[Backup Prompt Modal: Display the 1st prompt after the user receives their first transaction from another wallet(https://github.com/tari-project/wallet-android/issues/478)
