### ISSUE TITLE
Automated Backups

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#453]
See [parent](https://github.com/tari-project/wallet-ios/issues/447)

**Comment by Tas4tari** [comment]
Tested on Huawei P30 Lite, App version: v0.3.0-jnLibs-0.15.2
**Notes:**
When the user does a transaction I notice that the Backup indicator updates to Scheduled with a green tick
**Acceptance Criteria: Behavior**
**Cloud backups**

- Back up to the cloud after every single transaction
- When backup is being attempted/in progress/retried, status bar on tx list screen should always read "Backing up your wallet..." with success message appearing as "Backup successful!" before the status bar disappears
- If backup fails due to network connectivity, it should automatically start trying again once connectivity restored until it succeeds
- If cloud is out of storage AND user app is backgrounded, send them push notification reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full"
- If cloud is out of storage AND user app is in foreground, show modal reading "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" "OK" (they can always retry manually from settings after resolving the issue)
- If user is signed out of iCloud/Google drive, show same push notif and modal as above but body of message should read "You are not signed into iCloud" or "You are not signed into Google Drive"
- If user has cloud storage disabled, show same push notif and modal as above but body of message should read "You do not have iCloud enabled on your device" or "You do not have Google Drive enabled on your device"

**Android Only**
Start a timer w/ each transaction so it only backs up after 5 min to avoid multiple backups per transaction whenever possible
**Acceptance Criteria: UI/UX changes**
**Settings Screen**

- Change the “Back up wallet” setting in the security section to read “Wallet Backups” so it’s clearer you can go there to change your settings/see backup status: **Tested successfully**
- To the right of “Wallet Backups,” Instead of a green or red indicator as to whether the user has connected iCloud, let’s instead have an indicator and a label that tells the user the current status of the backups: “Up to date” or “Out of date” or “In progress” **Tested successfully [Except waiting for out of date back up option]
- Beneath “Wallet Backups,” add “Last successful backup: Mon D YYYY at HH:MM AM/PM”: **Tested successfully. As per the design we do not display the day**

**Wallet Backups Screen**

- iCloud backups should now display as a toggle. It’s switched off for new users, and then switched on once the user enables iCloud. User can switch it off to prevent the app from continuing to back up to iCloud (though it doesn’t delete the prior backups, that’s what the red link at the bottom is for!)
- New item called Back Up Now should be added that when tapped, forces a backup if one is not already in progress. Next to that item on the right, the same red/green/gray label and indicator from the prior screen should be added, and below it the same last backup timestamp as on the prior page should be added.

**Testing videos on Beta:**
**Wallet up to date:** https://drive.google.com/file/d/1kiOYQGpQBisi8zUmCht2SUwQw0O4VLCX/view?usp=sharing
**Backup scheduled:** https://drive.google.com/file/d/1Xvvr42qKltBebQog17dMyFBP-kkaYTCD/view?usp=sharing

**Comment by Tas4tari** [comment]
Created tickets for all the above that has failed testing so will close this ticket
cc @kukabi 

- https://github.com/tari-project/wallet-android/issues/483
- https://github.com/tari-project/wallet-android/issues/478
- https://github.com/tari-project/wallet-android/issues/482
- https://github.com/tari-project/wallet-android/issues/484
- https://github.com/tari-project/wallet-android/issues/485
