### ISSUE TITLE
Authentication is bypassed when opening the application via deeplink

### ISSUE THREAD

**Issue by sdbondi** [tari-project/wallet-android#508]
Thanks for @nyarian for reporting this! (See https://github.com/tari-project/tari/issues/2085)

Video journey: https://drive.google.com/file/d/19H91GEIcYzhD8NhY9FHnoG-smabvH5zL/view?usp=sharing

**Comment by nyarian** [comment]
So the indented behavior of the application turned out to be not the one I thought - if the app is backgrounded or killed but the wallet service is alive than the authentication not be present at all, and it should appear only if both the application and the wallet service are killed completely. Sorry for the confusion, I'm closing this ticket.
